#Options for connect transmission	
transmission:
  host: server.f6.lan
  port: 9091

options:
  preservDownload: yes
  preservState: yes
  preservFiles: yes

#Reg exp for parse comments
#exit on first match on input torrent comment, non pattern match - file is uniq
#when check all torrents in transmission with same pattern

comment-regs:
#[<regexp>,<pattern>] <pattern> for 
  - ['http://free-torrents.org/forum/viewtopic.php\?p\=(.*)', '\1']
  - ['http://nnm-club.me/forum/viewtopic.php\?p=(.*)', '\1']
  #- ['.*' , '\0']  adds automaticly